### ISSUE TITLE
Consolidating qualtrics data sources?

### ISSUE THREAD

**Issue by mekline** [melsod/ManyBabies1-Qualtrics#1]
@melsod , over in the main mb1 analysis repository, there's a single csv that seems to contain Qualtrics survey data:

https://github.com/langcog/mb1-analysis/tree/master/metadata

Should it be over here instead? Is it a duplicate of one of the other surveys?

**Comment by melsod** [comment]
That is an outdated version and should probably be deleted. Maybe check first to make sure it's not being used in the pipeline somewhere?

**Comment by rebeccalundwall** [comment]
@melsod  This is an update on the protocol change form Qualtrics output file.  I looked at how to incorporate emails you received before the change form was created  ([lab questionnaire updated info from May 2017 (to incorporate)_RAL.docx](https://github.com/melsod/ManyBabies1-Qualtrics/files/2385436/lab.questionnaire.updated.info.from.May.2017.to.incorporate._RAL.docx)). I made comments and highlighting in this document.  

In essence, I recommend adding three columns to the protocol change form Qualtrics output file.  Two columns should be self-explanatory, but the third column is a change/correction column, and I recommend putting the **old** information in this column and the new information into the column where it would exist if it had been included on the original lab questionnaire.  Here is what it would look like [ManyBabies1protocolchangeformrawMay22-2018_RAL.xlsx](https://github.com/melsod/ManyBabies1-Qualtrics/files/2385450/ManyBabies1protocolchangeformrawMay22-2018_RAL.xlsx)

**NOTE** I did make the switch for the change/correction column.  However, it looks like the new information was already in the column where it would exist if it had been on the original form, so the original information is not actually in the change/correction column.  I looked for it in the May 3 version, but I could not find old information there either (it looked like it had already been corrected by this point).

**Comment by rebeccalundwall** [comment]
Just FYI.  This is in response to @mekline 's suggestion that I change oto a human-readable form the column headers of 
[ManyBabies1LaboratoryQuestionnaireJune13-2018raw.csv.xlsx](https://github.com/melsod/ManyBabies1-Qualtrics/files/2385509/ManyBabies1LaboratoryQuestionnaireJune13-2018raw.csv.xlsx)
So, I created the human-readable labels ([for R rename.txt](https://github.com/melsod/ManyBabies1-Qualtrics/files/2385504/for.R.rename.txt)) and just need to write the R code to complete this task.

**Comment by mekline** [comment]
Hi Rebecca - let's make sure we don't duplicate work, and this is my fault
for not providing better docs!

Principle #1: The original datafiles live in the folder qualtricsraw/, and
are never changed! If we need to update to a newer download, we'll put the
new versions there and hope that the pipeline doesn't break (or fix it)  :)

Principle #2: All R code goes in qualtrics-data-formatting.R, so we can
always see the process of going from those static original files to the
final output.

So:

Check out the stub of qualtrics-data-formatting.R - this is where the three
'original' files get read in, and then we'll programmatically add those
better column names (in the pipeline, not modifying the original data
files.)  The program currently just prints out csvs to the metadata/ folder
called:

lab_debrief_dict_raw.csv
lab_questionnaire_raw.csv
secondary_dict_raw.csv

Then, there are version of these files called lab_debrief_dict_literate.csv
and so on - can you add the new names you made to these files? Then, your R
code for grabbing those names and adding them to the data frames should go
in qualtrics-data-formatting.R (where it says "#read in and add better
column names" :) )

**Comment by mekline** [comment]
(Sorry if I'm repeating anything, by the way! I'm offline until monday but
happy to help further then!)

**Comment by rebeccalundwall** [comment]
@mekline I teach all day on Monday, but would love a little more guidance about that time.  I am a little confused by your comments.  

I'm very sorry, but what did I say or do that made you think I was planning on changing any raw files (or any versions of files that are not of my creation)?  Was it when I talked about creating the R code for changing column name to human readable names?  I was only planning on creating the code, not executing it.  I think it probably needs to be inserted in the pipeline by someone who knows more about the pipeline then me.  I would never edit a file without first creating a new copy of the file in which to put my edits.

I understand about always seeing the process as a principle of Open Science. @melsod mentioned this when writing about edits made to the Qualtrics Protocol Change form output.  I support that everything needs to be done in R.  I am just making a plan at her suggestion.  The files are for illustration purposes only (so you know what I am thinking).  However, I can write code to rename headers in R.  I just won't execute it.

Anyway, I hope this clears up any concerns you had. Let's talk on Monday.  My cell is 713-817-3033.  I'm free atfter 5 pm MDT.  Thanks!

**Comment by mekline** [comment]
Hi Rebecca - sure, I'd be happy to chat with you - I'm not free today
though, do you have any time on Tuesday or Wednesday?

And I really apologize if I pitch any of my comments at the wrong level or
state things you already know - no offense meant! I find it helpful to be
more than usually explicit about this stuff when working remotely with a
large group (helps me to clarify my own thinking AND to document decisions
for future ppl coming across similar issues) but it's helpful to get
feedback when I get it wrong as well!

- Melissa

**Comment by mekline** [comment]
(@rebeccalundwall , where are the files you linked actually hosted right now? I don't see anything with the _RAL suffix you used in the master...)

**Comment by rebeccalundwall** [comment]
It’s fine. It is extremely difficult for me to get tone correct in written communication.  I was mostly just worried I had done something wrong or said something that made you think I had done something wrong.

I teach all day on Mondays, so no missed opportunity there.

I am free for
11 am – noon on Tuesday
11 am - 3 pm on Wednesday
9 am - 11 am Thursday

Will something in there work?

Rebecca A. (Becky) Lundwall, Ph.D.
Assistant Professor
Psychology Department and Neuroscience Center
1064 KMBL
Brigham Young University
Provo, UT 84602
Rebecca_Lundwall@byu.edu or Becky_Lundwall@byu.edu
https://cogdevelopment.byu.edu/

**Comment by mekline** [comment]
What time zone are those? Wednesday and Thursday mid-day (ET) have
scattered meetings but otherwise open for me :)

**Comment by rebeccalundwall** [comment]
MDT

Rebecca A. “Becky” Lundwall, Ph.D.
Assistant Professor
Psychology Department and Neuroscience Center
1064 KMBL
Brigham Young University
Provo, UT 84602
Rebecca_Lundwall@byu.edu<mailto:Rebecca_Lundwall@byu.edu> or Becky_Lundwall@byu.edu<mailto:Becky_Lundwall@byu.edu>
https://cogdevelopment.byu.edu/<https://cogdevelopment.byu.edu/Pages/home.aspx>

**Comment by rebeccalundwall** [comment]
Wednesday 8 am my time would be 10 am your time.  Can you do that?

Thursday 9 am my time (I have an 8 to 9 am meeting) would be 11 am your time.  Is that open for you?  If so, what number should I call?

Rebecca A. (Becky) Lundwall, Ph.D.
Assistant Professor
Psychology Department and Neuroscience Center
1064 KMBL
Brigham Young University
Provo, UT 84602
Rebecca_Lundwall@byu.edu or Becky_Lundwall@byu.edu
https://cogdevelopment.byu.edu/

**Comment by mekline** [comment]
Thursday 11am ET/9 MDT works, let's talk then! If we can skype, I'm at
melissa.e.k

**Comment by rebeccalundwall** [comment]
Mine is rebecca.lundwall

Unfortunately, I forgot that I do not have a camera or microphone on my office computer and I left my laptop at home.  I’ll have to use my phone.

Rebecca A. “Becky” Lundwall, Ph.D.
Assistant Professor
Psychology Department and Neuroscience Center
1064 KMBL
Brigham Young University
Provo, UT 84602
Rebecca_Lundwall@byu.edu<mailto:Rebecca_Lundwall@byu.edu> or Becky_Lundwall@byu.edu<mailto:Becky_Lundwall@byu.edu>
https://cogdevelopment.byu.edu/<https://cogdevelopment.byu.edu/Pages/home.aspx>
