### ISSUE TITLE
Labs who filled out initial questionnaire but don't appear in final dataset

### ISSUE THREAD

**Issue by mekline** [melsod/ManyBabies1-Qualtrics#8]
These lab IDs represent labs that filled out an initial questionnaire but don't have a corresponding dataset. @melsod are you able to confirm if these labs dropped out, or if I'm just failing to match the ID?

"elpgeorgetown"
"ellskidmore"       
"infantlabsingapore"/"nusbabylab"   
"mqcll"

**Comment by melsod** [comment]
ellskidmore, infantlabsingapore/nusbabylab, and mqcll all signed up but did not contribute data according to the various spreadsheets. I don't see anything for elpgeorgetown at all. I don't think we ever explicitly followed up with the labs who signed up but didn't contribute data - might be a good idea.

**Comment by mekline** [comment]
+1 - For both social reasons (did they have trouble? How could we help them
next time?) and statistical (on the off chance they dropped out because
they collected a subsample and peeked.)

**Comment by melsod** [comment]
Oh, the other place that someone could check @rebeccalundwall (?) would be the protocol change forms. If a lab formally dropped out, that's where they should be. I don't remember if any of these guys asked about that, but they may have and I forgot...

**Comment by melsod** [comment]
Also, there was at least one lab that only signed up for the gaze-following study - perhaps one or more of these guys did that.

**Comment by melsod** [comment]
OK, mq-cll has a formal withdrawal in the PCF.

**Comment by melsod** [comment]
OK, Georgetown is only signed up for gaze-following. So that just leaves ell-skidmore (Jess?) and nus-babylab (Leher), both of whom have been active in other aspects of the project. I will follow up with both.

**Comment by mekline** [comment]
Thanks!

**Comment by mekline** [comment]
Fixed in commit https://github.com/melsod/ManyBabies1-Qualtrics/commit/dc85e8c2b08885be6d6c1bb906e0369eb25d135e
